---
- uri:
    url: "{{ mandrill_inbounds_request_url }}"
    method: POST
    body:
      key: "{{ mandrill_api_key }}"
      domain: "{{ mandrill_inbound_domain }}"
    body_format: json
  vars:
    mandrill_operation: delete-domain