---
- include: add_domain.yml
  when: mandrill_inbound_key_operation == 'present'

- include: check_domain.yml
  when: mandrill_inbound_key_operation == 'check'

- include: delete_domain.yml
  when: mandrill_inbound_key_operation == 'absent'
